kind: PersistentVolume
apiVersion: v1
metadata:
  name: consul-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: null
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
